// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtPVq1kakUmYbMFtY3BJVZrm7ZuU1G1-s',
    appId: '1:493548552718:web:0ce3cee60fd1150e7c725f',
    messagingSenderId: '493548552718',
    projectId: 'unipal-271aa',
    authDomain: 'unipal-271aa.firebaseapp.com',
    storageBucket: 'unipal-271aa.firebasestorage.app',
    measurementId: 'G-9LH5X1QWG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKWH09_BTawn1TbFcl64z6Pa2F3W7CJpY',
    appId: '1:493548552718:android:32a59c69eb390fe37c725f',
    messagingSenderId: '493548552718',
    projectId: 'unipal-271aa',
    storageBucket: 'unipal-271aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4AkKGlMjamIf58NHCRvCdFM7mBE6JhdM',
    appId: '1:493548552718:ios:f58380c49f7b975c7c725f',
    messagingSenderId: '493548552718',
    projectId: 'unipal-271aa',
    storageBucket: 'unipal-271aa.firebasestorage.app',
    iosBundleId: 'com.example.unipal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4AkKGlMjamIf58NHCRvCdFM7mBE6JhdM',
    appId: '1:493548552718:ios:f58380c49f7b975c7c725f',
    messagingSenderId: '493548552718',
    projectId: 'unipal-271aa',
    storageBucket: 'unipal-271aa.firebasestorage.app',
    iosBundleId: 'com.example.unipal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtPVq1kakUmYbMFtY3BJVZrm7ZuU1G1-s',
    appId: '1:493548552718:web:890d743419a73f497c725f',
    messagingSenderId: '493548552718',
    projectId: 'unipal-271aa',
    authDomain: 'unipal-271aa.firebaseapp.com',
    storageBucket: 'unipal-271aa.firebasestorage.app',
    measurementId: 'G-H3ZDHKSSTF',
  );
}
